# Gemini model options:
#   models/gemini-1.5-pro-latest
#   models/gemini-1.5-pro-preview
#   models/gemini-1.5-flash-latest
#   models/gemini-1.5-flash-preview
#   models/gemini-pro
#   models/gemini-pro-vision
model_name: models/gemini-1.5-pro-latest
temperature: 0.4  # range 0.0–1.0
top_p: 0.1
max_output_tokens: 6000
prompt_file: 3. Report Generator/a. Prompts/Templator Prompt - Modified for Mammo.yaml
include_thoughts: true
thinking_budget: 3000
seed: 0
