model_name: models/gemini-1.5-pro-latest
temperature: 0.4
top_p: 0.1
max_output_tokens: 6000
prompt_file: 3. Report Generator/a. Prompts/Templator Prompt - Modified for Mammo.yaml
include_thoughts: true
thinking_budget: 3000
seed: 0
