name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r project_meta/requirements.txt
          pip install flake8 pytest
      - name: Lint
        run: flake8
      - name: Test
        run: pytest -q
